# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bb5651c4fa4fc686d83aacf26fe9a8a770ef03da916457bb2907f10e3ae5a28f70219854cdc8365ac1ea5ea7030d432d3b8c8f39d19b9063303c140193b81a4

test:
  secret_key_base: 1fa9633c7780d74403835d4d687e58699da48650b04ab1abf3e0e7d5003ae8443de8dbaeb2a74e5b3da8b13fcb73ee6ae18393fd6863b83409bcb61decdca7d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
